---
- hosts: all
  sudo: Yes
  tasks:
    - name: Execute netsat -su
      shell: netstat -su | grep -A 3 'Udp:' | awk '/errors/ {printf "host={{ ansible_hostname }} udp_errors=%s ", $1}' > /var/log/counters_{{ iface }}

    - name: Execute netsat -I=iface
      shell: netstat -I={{ iface }} | awk '
          BEGIN {a=b=" "}
          /{{ iface }}/ {a=$4; b=$5};
          END {printf "RX-ERR=%s RX-DRP=%s\n",a,b}
        ' >> /var/log/counters_{{ iface }}

    - name: Fetch summary data to local directory
      fetch: src=/var/log/counters_{{ iface }} dest=fetched/counters_{{ mydate }}/{{ ansible_hostname }}_{{ iface }} flat=yes

    - name: Delete remote sumary data
      file: path=/var/log/counters_{{ iface }} state=absent
