# Salida:
#<nombre_maquina>        <Ring_buffer>(punto 4)  <Interrupt Coalescense: rx_usecs>(punto 6)       <Driver y Versión>(punto 5)     <Firmware Version>(punto 5)     <Bus_info_ID>(punto 5)

---
- hosts: clients
  sudo: Yes
  tasks:
    - name: Execute ethtool -g
      shell: ethtool -g {{ iface }} | grep -A 1 'Current hardware' | awk '
          BEGIN {a=" "}
          /RX/ {a=$2};
          END {printf "host={{ ansible_hostname }} RX=%s ",a}
        ' > /var/log/hw_{{ iface }}

    - name: Execute ethtool -i
      shell: ethtool -i {{ iface }} | awk '
          BEGIN {a=b=c=d=" "}
          /driver/ {a=$2}
          /^version/ {b=$2}
          /firmware-version/ {c=$2}
          /bus-info/ {d=$2};
          END {printf "driver=%s version=%s firmware-version=%s bus-info=%s ",a,b,c,d}
        ' >> /var/log/hw_{{ iface }}

    - name: Execute ethtool -c
      shell: ethtool -c eth1|awk '
          BEGIN {a=" "}
          /rx-usecs:/ {a=$2};
          END {printf "rx-usecs=%s\n",a}
        ' >> /var/log/hw_{{ iface }}

    - name: Fetch summary data to local directory
      fetch: src=/var/log/hw_{{ iface }} dest=fetched/hw_{{ mydate }}/{{ ansible_hostname }}_{{ iface }} flat=yes

    - name: Delete remote sumary data
      file: path=/var/log/hw_{{ iface }} state=absent

  # post_tasks:
  #   - name: Create Summary of counters logs
  #     local_action: command ./parseresults_hw.py -i fetched/hw_{{ mydate }} -o fetched/Summary_HW_{{ mydate }}_{{ iface }}.txt
