---
- hosts: server
  tasks:

    - name: Execute iperf to emit imas_b multicast
      command: "iperf -u -c {{ iperf_multicast_imas_b }} -b {{ capacity }} -l 50k -t 30"
      async: 45
      poll: 5


- hosts: clients
  sudo: Yes
  pre_tasks:
    - name: Take the date
      local_action: shell date '+%F.%H:%M:%S'
      register: mydate

    - debug: var=mydate.stdout
  tasks:
    - name: Fetch iperf log (local directory is fetched/iperf_date)
      fetch: src=/var/log/{{ iperf_service_name_imas_b }} dest=fetched/iperf_imas_b_{{ mydate.stdout }}/imas_b_{{ ansible_hostname }} flat=yes

    - name: Delete iperf log imas_b
      file: path=/var/log/{{ iperf_service_name_imas_b }} state=absent
      notify: Reiniciar iperf imas_b

  post_tasks:
    - name: Display a results of logs 
      local_action: command ./parseresults_iperf.py -t imas_b -i fetched/iperf_imas_b_{{ mydate.stdout }} -o fetched/Summary_iperf_imas_b_{{ mydate.stdout }}.txt

  handlers:
      - name: Reiniciar iperf imas_b
        service: name={{ iperf_service_name_imas_b }} state=restarted
