---
- hosts: server
  tasks:
    - name: Execute iperf to emit imas_a multicast
      command: "iperf -u -c {{ iperf_multicast_imas_a }} -b {{ capacity }} -l 50k -t 30"
      async: 45
      poll: 5

- hosts: clients
  sudo: Yes
  tasks:
    - name: Fetch iperf log (local directory is fetched/iperf_date)
      fetch: src=/var/log/{{ iperf_service_name_imas_a }} dest=fetched/iperf_imas_a_{{ mydate }}/imas_a_{{ ansible_hostname }} flat=yes

    - name: Delete iperf log imas_a
      file: path=/var/log/{{ iperf_service_name_imas_a }} state=absent
      notify:
        - Restart iperf imas_a

  handlers:
      - name: Restart iperf imas_a
        service: name={{ iperf_service_name_imas_a }} state=restarted
