---
- hosts: server
  tasks:
    - name: Execute msend to emit imas_a multicast
      command: "msend -m50000 -b5 -n500 -p8 -s1 {{ mdump_multicast_imas_b }} {{ mdump_multicastport }} 5 {{ ip_imas_b }}"
      async: 45
      poll: 5

- hosts: clients
  sudo: Yes
  tasks:
    - name: Fetch mtools log (local directory is fetched/mtools_date)
      fetch: src=/var/log/{{ mdump_service_name_imas_b }} dest=fetched/mtools_imas_b_{{ mydate }}/imas_b_{{ ansible_hostname }} flat=yes

    - name: Delete mtools log imas_b
      file: path=/var/log/{{ mdump_service_name_imas_b }} state=absent
      notify: Restart mtools imas_b

  handlers:
    - name: Restart mtools imas_b
      service: name={{ mdump_service_name_imas_b }} state=restarted
