---
- hosts: server
  tasks:
    - name: Execute msend to emit imas_a multicast
      command: "msend -m50000 -b5 -n500 -p8 -s1 {{ mdump_multicast_imas_a }} {{ mdump_multicastport }} 5 {{ ip_imas_a }}"
      async: 45
      poll: 5

- hosts: clients
  sudo: Yes
  tasks:
    - name: Fetch mtools log (local directory is fetched/mtools_date)
      fetch: src=/var/log/{{ mdump_service_name_imas_a }} dest=fetched/mtools_imas_a_{{ mydate }}/imas_a_{{ ansible_hostname }} flat=yes

    - name: Delete mtools log imas_a
      file: path=/var/log/{{ mdump_service_name_imas_a }} state=absent
      notify: Restart mtools imas_a

  handlers:
    - name: Restart mtools imas_a
      service: name={{ mdump_service_name_imas_a }} state=restarted
