---
- hosts: all
  sudo: yes
  tasks:
    - name: Comprobar con ping
      action: ping

    # - name: Copy mtools rpm
    #   copy: src=files/open-mtools-1.0-1.fc20.x86_64.rpm dest=/tmp/open-mtools-1.0-1.fc20.x86_64.rpm
    #
    # - name: Install mtools rpm
    #   command: "/bin/rpm -Uvh /tmp/open-mtools-1.0-1.fc20.x86_64.rpm"


- hosts: clients
  sudo: yes
  tasks:
    # note the other tasks on "all" hosts
    - name: Add mtools daemon imas_a init.d eth0 script
      template: src=templates/init.d-mdump_imas_a.j2 dest=/etc/init.d/{{ mdump_service_name_imas_a }} mode=0751
      notify:
        - Reiniciar mtools imas_a

    - name: Añadir iperf daemon imas_b init.d eth1 script
      template: src=templates/init.d-mdump_imas_b.j2 dest=/etc/init.d/{{ mdump_service_name_imas_b }} mode=0751
      notify:
        - Reiniciar mtools imas_b

  handlers:
      - name: Reiniciar mtools imas_a
        service: name={{ mdump_service_name_imas_a }} state=restarted

      - name: Reiniciar iperf imas_b
        service: name={{ mdump_service_name_imas_b }} state=restarted
